name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: gofmt
      run: gofmt -l -d . | (! grep . -q) || exit 1

    - name: Go Vet
      run: go vet ./...

    - uses: dominikh/staticcheck-action@v1.2.0
      with:
        version: "2023.1.6"
        install-go: false

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
